<?php
include_once("common.php");
include_once("../../Backend/connection.php");
session_start();
if(!isset($_SESSION["admin"])){
    if(!isset($_SESSION["username"])){
        header("Location: ./default.php");
        exit();
    } 
}
if(isset($_SESSION["admin"])){
    header("Location: ./admin.php");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticketing System</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            background-color: white;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 500px;
            text-align: center;
        }

        header {
            background-color: yellow;
            padding: 10px;
        }

        header h1 {
            margin: 0;
            font-size: 24px;
        }

        header p {
            margin: 0;
            font-size: 14px;
        }

        .movie-info {
            margin: 20px 0;
            text-align: left;
        }

        .movie-info p {
            margin: 5px 0;
        }

        .seat-selection {
            margin: 20px 0;
        }

        .screen {
            background-color: #ccc;
            padding: 10px;
            margin-bottom: 10px;
        }

        .seats {
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            gap: 10px;
        }

        .seat {
            width: 30px;
            height: 30px;
            background-color: #90EE90;
            cursor: pointer;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .seat.selected {
            background-color: #6495ED;
        }

        .seat.sold {
            background-color: red;
            cursor: not-allowed;
        }

        .actions {
            margin-top: 20px;
        }

        button {
            padding: 10px 20px;
            margin: 0 10px;
            border: none;
            background-color: red;
            color: white;
            cursor: pointer;
        }

        button#cancel {
            background-color: #ccc;
            color: black;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>TICKETING</h1>
            <p>...GET YOUR LUCKY SEAT, INSTANTLY.</p>
        </header>
        <div class="movie-info">
            <p><strong>Movie name:</strong> Inception</p>
            <p><strong>Category:</strong> 1.0</p>
            <p><strong>Genre:</strong> Sci-Fi</p>
            <p><strong>Ratings:</strong> 8.7</p>
            <p><strong>Show Time:</strong> 2024-06-15 14:00:00</p>
        </div>
        <div class="seat-selection">
            <div class="screen">Screen</div>
            <div class="seats">
                <!-- Rows and seats will be generated by JavaScript -->
            </div>
        </div>
        <div class="actions">
            <button id="select-seats">SELECT SEAT(S)</button>
            <button id="cancel">CANCEL</button>
        </div>
        <!-- Hidden fields for movieId and userId -->
        <input type="hidden" id="movieId" value="">
        <input type="hidden" id="userId" value="">
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
   document.addEventListener('DOMContentLoaded', () => {
       const seats = [
           ['A1', 'A2', 'A3', 'A4', 'A5'],
           ['B1', 'B2', 'B3', 'B4', 'B5'],
           ['C1', 'C2', 'C3', 'C4', 'C5'],
           ['D1', 'D2', 'D3', 'D4', 'D5'],
           ['E1', 'E2', 'E3', 'E4', 'E5']
       ];

       const soldSeats = ['A1', 'A2', 'D2', 'E3', 'E4'];
       const seatContainer = document.querySelector('.seats');
       const movieId = getUrlParameter('movieId');
       const userId = getUserIdFromSession(); // Implement this function to get user ID from the session

       // Set hidden field values
       document.getElementById('movieId').value = movieId;
       document.getElementById('userId').value = userId;

       seats.forEach(row => {
           row.forEach(seat => {
               const seatElement = document.createElement('div');
               seatElement.classList.add('seat');
               if (soldSeats.includes(seat)) {
                   seatElement.classList.add('sold');
                   seatElement.innerText = 'Sold';
               } else {
                   seatElement.innerText = seat;
                   seatElement.addEventListener('click', () => {
                       seatElement.classList.toggle('selected');
                   });
               }
               seatContainer.appendChild(seatElement);
           });
       });

       document.getElementById('select-seats').addEventListener('click', () => {
           const selectedSeats = document.querySelectorAll('.seat.selected');
           if (selectedSeats.length > 0) {
               const selectedSeatIds = Array.from(selectedSeats).map(seat => seat.innerText);
               const movieId = document.getElementById('movieId').value;
               const userId = document.getElementById('userId').value;
               console.log(selectedSeatIds);

               $.ajax({
                   url: '../../Backend/PHP/reserveSeats.php',
                   type: 'POST',
                   data: {
                       movieId: movieId,
                       userId: userId,
                       seats: selectedSeatIds
                   },
                   success: function(response) {
                       console.log(response);
                       if (response.success) {
                           alert('Seats successfully reserved!');
                           // Redirect to order.php with movieId as a parameter
                           window.location.href = `order.php?movieId=${movieId}`;
                       } else {
                           alert('Error reserving seats: ' + response.error);
                       }
                   },
                   error: function(xhr, status, error) {
                       console.error('AJAX error:', error);
                       console.error('XHR:', xhr);
                       console.error('Status:', status);
                       console.error('Response Text:', xhr.responseText); // Log the response text
                       alert('AJAX error: ' + error);
                   }
               });
           } else {
               alert('No seats selected');
           }
       });

       document.getElementById('cancel').addEventListener('click', () => {
           document.querySelectorAll('.seat.selected').forEach(seat => seat.classList.remove('selected'));
       });
   });

   function getUrlParameter(name) {
       name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
       const regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
       const results = regex.exec(location.search);
       return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
   }

   // This is a placeholder; implement according to your session management
   function getUserIdFromSession() {
       // For example, you might store user info in localStorage or retrieve it from a server-side session
       return '1'; // Replace with actual user ID retrieval logic
   }
</script>

</body>
</html>
